services:
  nginx:
    image: nginx:1.19.6-alpine
    depends_on:
      - php-fpm
      - frontend
    restart: unless-stopped
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./backend:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

  php-fpm:
    container_name: ${APP_NAME}_php-fpm
    build:
      context: ./docker
      dockerfile: php-fpm/Dockerfile
      args:
        - TZ=${TZ}
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

  php-cli:
    container_name: ${APP_NAME}_php-cli
    build:
      context: ./docker
      dockerfile: php-cli/Dockerfile
      args:
        - TZ=${TZ}
    volumes:
      - ./backend:/app
      - composer:/root/.composer/cache

  postgres:
    build:
      context: ./docker
      dockerfile: postgres/Dockerfile
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/postgres/app:/app
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-test_db}
      POSTGRES_USER: ${POSTGRES_USER:-test_db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test_db_password}
      PGDATA: /var/lib/postgresql/data/pgdata

  frontend:
    container_name: ${APP_NAME}_frontend
    restart: "no"
    volumes:
      - ./frontend/:/app
      - node_modules:/app/node_modules/
    build:
      context: ./frontend
    command: npm run dev

volumes:
  composer:
  postgres:
  node_modules:
